use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'JoyWKWeb_Example' do
  pod 'JoyWKWeb', :path => '../'

  target 'JoyWKWeb_Tests' do
    inherit! :search_paths

    
  end
end
